### ISSUE TITLE
Possibly incomplete typings for Webpack configuration

### ISSUE THREAD

**Issue by JuraFajt** [Oriflame/lumos#1174]
When trying to use this code:

```ts
import { WebpackConfig } from '@oriflame/lumos';

const config: WebpackConfig = {
  devServer: { ... },
};
```

the linter screams the following error:

```
Type '{ devServer: { headers: { 'Access-Control-Allow-Origin': string; 'Service-Worker-Allowed': string; }; host: string; port: number; proxy: { '/application': { changeOrigin: boolean; onProxyReq: (proxyReq: any) => void; target: string; }; '/system': { changeOrigin: boolean; onProxyReq: (proxyReq: any) => void; target: ...' is not assignable to type 'WebpackConfig'.
  Object literal may only specify known properties, and 'devServer' does not exist in type 'WebpackConfig'.ts(2322)
```
  
Without the type definition, it works just fine.

**Comment by rozsival** [comment]
Possible root causes:

- Typings for `webpack` and `webpack-dev-server` rely on declaration merging
- Beemo driver for `webpack` does not include `devServer` prop in allowed `webpack` args

We should most probably construct our own `WebpackConfig` interface with explicitly listed `devServer` property and its shape, if possible.

**Comment by JuraFajt** [comment]
Wouldn't it be possible to add the devServer as allowed prop into Beemo, or is such change considered to be a bad option?

**Comment by jakubmazanec** [comment]
Good luck getting Beemo updated, since author doesn't respond: https://github.com/beemojs/beemo/issues/159 🤦‍♂️

**Comment by JuraFajt** [comment]
I see. Thanks for information!

**Comment by rozsival** [comment]
@JuraFajt @jakubmazanec This could be at least a temporary solution: #1176.
