### ISSUE TITLE
eslint-plugin-unicorn incompatible with eslint 8.40

### ISSUE THREAD

**Issue by rozsival** [Oriflame/lumos#1202]
We need to upgrade `eslint-plugin-unicorn` to at least `v46.0.1` as previous versions have compatibility issues with latest `eslint`.

See: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2076

**Comment by jakubmazanec** [comment]
I updated both to the latest version. You may check if it helped.

**Comment by rozsival** [comment]
It works, thanks!
